export const IMAGES = {
    Logo: require('../assets/images/Logo.png'),
    Calender: require('../assets/images/calender.png'),
    Envelope: require('../assets/images/envelope.png'),
    Phone: require('../assets/images/phone.png'),
    User: require('../assets/images/user.png'),
    Mask: require('../assets/images/mask.png'),
    Eye: require('../assets/images/eye.png'),
    Lock: require('../assets/images/lock.png'),
    DownArrow: require('../assets/images/downArrow.png'),
    LeftArrow: require('../assets/images/leftArrow.png'),
    BloodDrop: require('../assets/images/bloodDrop.png'),
    BottomHome: require('../assets/images/bottomHome.png'),
    BottomProfile: require('../assets/images/bottomProfile.png'),
    BottomCalender: require('../assets/images/bottomCalender.png'),
    BottomTrend: require('../assets/images/bottomTrend.png'),
    Cart: require('../assets/images/cart.png'),
    Location: require('../assets/images/location.png'),
    Notification: require('../assets/images/notification.png'),
    SosAlert: require('../assets/images/sosAlert.png'),
    Add:require('../assets/images/add.png'),
    Search:require('../assets/images/search.png'),
    bloodDrop:require('../assets/images/bloodDrop.png'),
    blood:require('../assets/images/blood.png'),
    Colon:require('../assets/images/Colon.png'),
    Heart:require('../assets/images/Heart.png'),
    kidney:require('../assets/images/kidney.png'),
    liver:require('../assets/images/liver.png'),
    Lungs:require('../assets/images/Lungs.png'),
    Dr:require('../assets/images/Dr.png'),
    Pancreatitis:require('../assets/images/Pancreatitis.png'),
    Thermometer:require('../assets/images/Thermometer.png'),
    Thyroidtest:require('../assets/images/Thyroidtest.png'),
    Thyroid:require('../assets/images/Thyroid.png'),
    urine:require('../assets/images/urine.png'),
    Bones:require('../assets/images/Bones.png'),
    testtube:require('../assets/images/testtube.png'),
    searchInsta:require('../assets/images/searchInsta.png'),
    ix_ai:require('../assets/images/ix_ai.png'),
    check:require('../assets/images/check.png'),
    water:require('../assets/images/water.png'),
    Tea:require('../assets/images/Tea.png'),
    food:require('../assets/images/food.png'),
    close:require('../assets/images/close.png'),
    Black:require('../assets/images/Black.png'),
    back:require('../assets/images/back.png'),
    remove:require('../assets/images/remove.png'),



}