export const IMAGES = {
    Logo: require('../assets/images/Logo.png'),
    Calender: require('../assets/images/calender.png'),
    Envelope: require('../assets/images/envelope.png'),
    Phone: require('../assets/images/phone.png'),
    User: require('../assets/images/user.png'),
    Mask: require('../assets/images/mask.png'),
    Eye: require('../assets/images/eye.png'),
    Lock: require('../assets/images/lock.png'),
    DownArrow: require('../assets/images/downArrow.png'),
    LeftArrow: require('../assets/images/leftArrow.png'),
    BloodDrop: require('../assets/images/bloodDrop.png'),
    BottomHome: require('../assets/images/bottomHome.png'),
    BottomProfile: require('../assets/images/bottomProfile.png'),
    BottomCalender: require('../assets/images/bottomCalender.png'),
    BottomTrend: require('../assets/images/bottomTrend.png'),
    Cart: require('../assets/images/cart.png'),
    Location: require('../assets/images/location.png'),
    Notification: require('../assets/images/notification.png'),
    SosAlert: require('../assets/images/sosAlert.png'),
    Add:require('../assets/images/add.png'),
    Search:require('../assets/images/search.png'),
    SearchInsta:require('../assets/images/searchInsta.png')

}